apiVersion: apps/v1
kind: Deployment
metadata:
  name: first
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: first
  template:
    metadata:
      labels:
        app: first
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: first
        ports:
        - containerPort: 80